services: 
  icap-clamav:
    container_name: icap-clamav
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "1344:1344"
    volumes:
      - ./signatures:/var/lib/clamav
    cap_add:
      - CAP_NET_RAW
      - CAP_NET_ADMIN
